services:
  postgres-server:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-server
  
  webapi:
    build:
      context: .
      dockerfile: /AutoBuy.WebApi/Dockerfile
      no_cache: true
    ports:
      - "5000:8080"
    environment:
      POSTGRESQL_CONNECTIONSTRING: Server=postgres-server;Port=5432;Database=data;User Id=admin;Password=password; Include Error Detail = true;
      PLAYWRIGHT_SERVER: null

volumes:
  pgdata:
  pgadmin-data:
    
